services:
  api:
    build: .
    container_name: fast-auth
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    networks:
      - default
    volumes:
      - .:/app
      - /app/.venv
    # local dev only
    command: >
      uv run uvicorn src:app
      --host 0.0.0.0
      --port 8000
      --reload

  postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:16-alpine
    container_name: auth-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_test
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_test"]
      interval: 2s
      timeout: 2s
      retries: 10
      

  redis:
    image: redis:7-alpine
    container_name: auth-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - default
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:

