"""create session and revoke token tables

Revision ID: 206207ab5303
Revises: c45fc268c617
Create Date: 2026-05-25 15:21:10.496374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '206207ab5303'
down_revision: Union[str, Sequence[str], None] = 'c45fc268c617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('revoked_at IS NULL or revoked_at >= created_at', name='check_session_revocation'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_user_id_is_revoked', 'sessions', ['user_id', 'is_revoked'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('parent_token_id', sa.UUID(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name='chk_token_expiry'),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name='chk_token_revocation'),
    sa.ForeignKeyConstraint(['parent_token_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_family_revoked', 'refresh_tokens', ['family_id', 'is_revoked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_family_revoked', table_name='refresh_tokens')
    op.drop_index('ix_refresh_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_session_user_id_is_revoked', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
