"""refactor sessions table

Revision ID: 998e6d7c6af0
Revises: cf5f57aa0f99
Create Date: 2026-06-07 14:12:38.870615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998e6d7c6af0'
down_revision: Union[str, Sequence[str], None] = 'cf5f57aa0f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersessions', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_session_user_id_is_revoked'), table_name='usersessions')
    op.create_index('ix_session_user_id', 'usersessions', ['user_id'], unique=False)
    op.drop_column('usersessions', 'is_revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersessions', sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('ix_session_user_id', table_name='usersessions')
    op.create_index(op.f('ix_session_user_id_is_revoked'), 'usersessions', ['user_id', 'is_revoked'], unique=False)
    op.drop_column('usersessions', 'expires_at')
    # ### end Alembic commands ###
