"""change session table name

Revision ID: cf5f57aa0f99
Revises: 206207ab5303
Create Date: 2026-06-03 18:13:34.678460

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf5f57aa0f99"
down_revision: Union[str, Sequence[str], None] = "206207ab5303"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usersessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "revoked_at IS NULL or revoked_at >= created_at",
            name="check_session_revocation",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_session_user_id_is_revoked"), table_name="sessions")
    op.create_index(
        "ix_session_user_id_is_revoked",
        "usersessions",
        ["user_id", "is_revoked"],
        unique=False,
    )
    op.drop_constraint(
        op.f("refresh_tokens_session_id_fkey"), "refresh_tokens", type_="foreignkey"
    )
    op.drop_table("sessions")
    op.create_foreign_key(
        None,
        "refresh_tokens",
        "usersessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_tokens_session_id_fkey"),
        "refresh_tokens",
        "sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "user_agent", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
        sa.Column("ip_address", postgresql.INET(), autoincrement=False, nullable=True),
        sa.Column("is_revoked", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "revoked_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= created_at",
            name=op.f("check_session_revocation"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("sessions_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
    )
    op.create_index(
        op.f("ix_session_user_id_is_revoked"),
        "sessions",
        ["user_id", "is_revoked"],
        unique=False,
    )
    op.drop_index("ix_session_user_id_is_revoked", table_name="usersessions")
    op.drop_table("usersessions")
    # ### end Alembic commands ###
